version: "3.1"
services:
  cart-api:
    container_name: cart
    env_file: 
      - .env   
    build: ./
    ports:
      - '8084:${PORT}'
    volumes:
      - ./:/go/src/github.com/julioshinoda/cart
  swagger-ui:
   image: swaggerapi/swagger-ui
   container_name: swagger_ui_container
   ports:
      - "8091:8080"
   volumes:
      - ./doc:/usr/share/nginx/html/doc
   environment:
      API_URL: doc/cart-doc.yaml 
  redis:
    image: redis
    ports:
      - "6379:6379"      