version: "3.1"
services:
  swagger-ui:
   image: swaggerapi/swagger-ui
   container_name: swagger_ui_container
   ports:
      - "8091:8080"
   volumes:
      - ./doc:/usr/share/nginx/html/doc
   environment:
      API_URL: doc/cart-doc.yaml 
  redis:
    image: redis
    ports:
      - "6379:6379"      