// Code generated by mockery v2.9.3. DO NOT EDIT.

package mocks

import (
	entity "github.com/julioshinoda/cart/entity"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *Repository) Get(id string) (*entity.Cart, error) {
	ret := _m.Called(id)

	var r0 *entity.Cart
	if rf, ok := ret.Get(0).(func(string) *entity.Cart); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Cart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: e
func (_m *Repository) Update(e *entity.Cart) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Cart) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
